### ISSUE TITLE
F-16 ControlStick/Base.SLDPRT

### ISSUE THREAD

**Issue by regorpet** [JonahTsai/F16#2]
I try to convert the file  ControlStick/Base.SLDPRT, but it seems to be something wrong with the file. Can you check if it's OK. Maybe you have it in STL format ?

**Comment by JonahTsai** [comment]
The file is just fine, both inside my private repo at home and the one at GitHub.

I could open and convert both to STL files (one downloaded from GitHub), just now. Both are fine. The generated STL is over 11.5MB, as opposed to about 778KB for the SolidWork file.

Like I mentioned somewhere else... there are reasons why I no longer publish STL files.
1. STL files are much more difficult to modify than SolidWorks files. These files are not design files... I have no idea about your material, manufacturing methods etc. You most likely will have to modify them to suit your material/tools/manufacturing/skill choices. For instance, STL is completely useless if you are going to CNC mill the thing.
2. Even if you could use the model completely unmodified (this base is certainly not one of them), and you are going to 3D print it, I have no idea what your nozzle size will be, or what kinds of precision your 3D printer can do so I can determine the size of the mesh to generate.
3. Sometimes, to achieve the desired precision, the file size generated could be real big... the F16 TQS STL files I generated for bronze lost wax casting is about 350MB. They are too big to store each revision of 300MB in repositories. Not to mention, storing large regenerable files in repositories is just plain stupid.

So, I am suspecting the tool you use to convert it to STL might be the problem?

**Comment by regorpet** [comment]
OK. Thanks for your reply, you might be right 
Kind regards 
Roger
